#!/bin/bash

#For this script you need to install vnstat!!!

wifiNet="wlp4s0"

strindex() {
	 x="${1%%"$2"*}"
	[[ "$x" = "$1" ]] && echo -1 || echo "${#x}"
}

ratestr()
{
	s=$1
	id=`strindex "$s" "mbit/s"`
	if (( $id >= 0 ))
	then
		s=${s:0:$((id-1))}
		s="$s"mb/s
		echo $s
	else
		id=`strindex "$s" "kbit/s"`
		if (( $id >= 0 ))
		then
			s=${s:0:$((id-1))}
			s="$s"kb/s
			echo $s
		else
			id=`strindex "$s" "bit/s"`
			if (( $id >= 0 ))
			then
				s=${s:0:$((id-1))}
				s="$s"b/s
				echo $s
			fi
		fi
	fi

}


console=$1
if [ -n "$console" ]
then
	console=/dev/$console
else
	console=/dev/ttyUSB0
fi

stty -F $console 0:4:1cb2:0:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
#stty -F $console 115200
sleep 0.5

rm /tmp/wifi.log
vnstat -l -i $wifiNet --json >> /tmp/wifi.log &

while ((1))
do
	echo -e "CpuLoad=`./cpu_info cpu`\n" > $console

	temp=`cat /sys/class/thermal/thermal_zone0/temp`
	temp=$((temp/1000))
	echo -e "DateStr=`date +"%d/%m/%Y"`\n" > $console
	echo -e "TimeStr=`date +"%H:%M"`\n" > $console
	
	echo -e "CpuTemp=$temp\n" > $console
	
	
	strmem=`./cpu_info mem`
	memall=`echo $strmem | awk '{ print $1 }'`
	memusemb=`echo $strmem | awk '{ print $2 }'`
	memuse=`echo $strmem | awk '{ print $3 }'`
	echo -e "RamUsage=$memuse\n" > $console
	echo -e "RamAll=$memall\n" > $console
	echo -e "RamUse=$memusemb\n" > $console
	
	strhdd=`df -h / | grep "/"`
	hddAll=`echo $strhdd | awk '{ print $2 }' | head -c -2
`	hddFree=`echo $strhdd | awk '{ print $4 }' | head -c -2`
	hddUseMb=`echo $strhdd | awk '{ print $3 }' | head -c -2`
	hddUse=$((hddUseMb*100/hddAll))
	echo -e "HddUseMem=$hddUse\n" > $console
	echo -e "HddAllMem=$hddAll\n" > $console
	echo -e "HddFreeMem=$hddFree\n" > $console

	vol=`amixer -c 1 -M -D pulse get Master | grep -m 1 -o -E '[[:digit:]]+%' | head -c -2`
	echo -e "Volume=$vol\n" > $console

	wifiLink=`ip a | grep $wifiNet | grep "state UP"`
	if [ -n "$wifiLink" ]
	then
		wifiLink=1
	else
		wifiLink=0
	fi
	echo -e "WiFiStatus=$wifiLink\n" > $console
	
	wifiUp=""
	wifiDl=""
	str=`cat /tmp/wifi.log | tail -1`
	id=`strindex "$str" "\"rx\":{\"ratestring\":"`
	wifiUp=${str:$((id+20))}
	str=${str:$((id+20))}
	id=`strindex "$wifiUp" "\""`
	wifiUp=${wifiUp:0:$((id))}

	id=`strindex "$str" "\"tx\":{\"ratestring\":"`
	wifiDl=${str:$((id+20))}
	id=`strindex "$wifiDl" "\""`
	wifiDl=${wifiDl:0:$id}
	
	wifiUp=`ratestr "$wifiUp"`
	wifiDl=`ratestr "$wifiDl"`
	
	echo -e "WifiUpSpeed=$wifiUp\n" > $console
	echo -e "WifiDlSpeed=$wifiDl\n" > $console
	#sleep 0.5
done




