#!/bin/bash

#For this script you need to install vnstat!!!


while ((1))
do
	#echo 333 >> /tmp/ddd.log
	amixer -c 1 -M -D pulse get Master | grep -m 1 -o -E '[[:digit:]]+%' | head -c -2 > /tmp/vol
	#pactl get-sink-volume 0 >> /tmp/ddd.log 2>$1
	sleep 1

done





